name: Update Documentation

on: push

permissions:
  contents: write

jobs:

  update-content:
    name: Update Content
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer:v2

      - name: Install tooling
        run: composer install

      - name: Update Content
        run: php parser.php --update